### PR TITLE
Lazy load commands

### PR DESCRIPTION
**Pull request by enekochan**
Auto-registration of commands is not supported in Symfony >= 4.0

### CODE REVIEW

**Comment by enekochan** [comment]
@sanpii Hi, could you please review and merge this PR? Without this some deprecation warnings for Symfony 3.4 appear and make this bundle not fully work in Symfony 4.0. Thank you!

**Comment by sanpii** [comment]
Sorry for the delay.

Why are you creating a `defaultName` property? It’s not necessary (you can overwrite the `configure` method) and unrelated to the subject of this PR. But I maybe miss something…

**Comment by enekochan** [comment]
It's used for [Lazy Loading](https://symfony.com/doc/current/console/commands_as_services.html#lazy-loading) and other libraries like FOSUserBundle do it this way. May by it's redundant if command tag is used.

**Comment by sanpii** [comment]
Ok, thank you !

**Pull request merged**
